# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Arm Controllers ---------------------------------------
arm_controller:
   type: "position_controllers/JointTrajectoryController"
   joints:
     - base_link__link_01
     - link_01__link_02
     - link_02__link_03
     - link_03__link_04
     - link_04__link_05
     - link_05__link_06
     - link_06__link_07
      

# Hand controller ---------------------------------------
hand_controller:
   type: "position_controllers/JointTrajectoryController"
   joints:
     - link_08__link_09
     - link_08__link_10